### ISSUE TITLE
Role syncing not requiring the same names

### ISSUE THREAD

**Issue by SSRPStevens** [techy2493/ts-disc-control#7]
Biggest issue I currently have is requiring the Discord role and the TeamSpeak role to be named the same. Is causing some workflow difficulties when it comes to getting things setup. Thank you!

**Comment by techy2493** [comment]
Update roles table to add TS Group ID column, ensure both ids are unique. Update sync and unsync commands to allow for managing this, using TS group name to get the ID, and add error messages when unique constraint is violated which provides the current config'd names. Sync command should prompt user to override existing value(s) with button inputs. While editing make both commands inherit /tsid's config'd permission and allow add one additional config to provide a separate role for these commands permissions.
