### ISSUE TITLE
/tsid restriction customization

### ISSUE THREAD

**Issue by SSRPStevens** [techy2493/ts-disc-control#8]
Ability to configure Discord Role IDs permitted to use /tsid, on top of this some documentation on who is permitted to use it as currently I am not 100% sure.

**Comment by techy2493** [comment]
Currently only users with the Discord Manage Roles permission can call TSID
We should make this configurable with a config setting. Probably in the discord config object.

**Comment by techy2493** [comment]
Implemented by #10
